### ISSUE TITLE
linear variables in P

### ISSUE THREAD

**Issue by shazqadeer** [p-org/P#100]
I have added a feature for linear memory management to P.  I am writing this post to encourage you to try it out and provide feedback.  

The problem I am trying to solve is to reduce the cost of cloning when values are passed as arguments to a function or sent across machines as the payload of an event.  My implementation is in two parts.  First, I have introduced the notion of pure functions as those that do not modify globals or input parameters.  Purity is inferred automatically by the P compiler.  A call to a pure function is optimized by not cloning the input parameters.  For functions that are not pure, I have introduced the notion of passing parameters by transfer (indicated by keyword “xfer”) or by exchange (indicated by keyword “swap”). “xfer” or “swap” parameters can only be local variables in the caller. Passing a parameter by “xfer” means that the caller is relinquishing rights to access that parameter.  Passing a parameter by “swap” means that the caller wants updates to the parameter made inside the callee to be made visible when the call returns.  In both cases, the input value is not cloned.  

fun foo(a: int) {
    a = 1;
} 

fun bar() {
  var x, y: int;

  x = 0;
  foo(x swap);
  assert x == 1;   // succeeds at runtime
  foo(x xfer);
  y = x + 1;            // compile-time error
}

In the example above, in the function “bar”, x is passed as “swap” in the first call to foo.  Consequently, the value of x is 1 right after the call. x is passed as “xfer” in the second call to foo.  Consequently,  it is illegal to access it right after the call as the ownership of the memory used to hold its contents has been given away.  This error is detected by the compiler.  The following revision of bar does not result in any compile-time errors because the assignment of 42 to x puts a fresh value into x.

fun bar() {
  var x, y: int;

  x = 0;
  foo(x swap);
  assert x == 1;   // succeeds at runtime
  foo(x xfer);
  x = 42;
  y = x + 1;  
}

The programmer may select certain parameters of a multi-parameter function to pass with “xfer” or swap”.  For example:

baz(x swap, y, z xfer);     // ok

The compiler ensures that the same variable is not passed in two positions as “xfer” or “swap”

bar(x swap, y, x xfer);     // compile-time error

The ability to pass only  local variables as “xfer” or “swap” parameters to functions is restrictive.  What about global variables or fields of tuples or entries in sequence or a map?  To  make the solution more general, I allow assignment operation to be annotated with “xfer” or “swap” as well.  For example:

g = l xfer;             // g is global in a machine, l is local to a function

x[v] = l swap;      // l is local to a function, x is either a (global or local) sequence or map

The first assignment moves ownership of the memory behind l to g; l cannot be used after this assignment until a fresh value is put into it.  The second assignment swaps the contents of x[v] and l; l can continue to be used after this assignment.  By appropriately combining “xfer” or “swap” assignments with “xfer” or “swap” parameter passing, cloning can be reduced significantly.

Finally, “xfer” can be used with send and raise as well.

send t, e, v1, v2 xfer;      // send machine t event e with payload (v1, v2) where v1 is passed normally and v2 is passed by “xfer”
raise e, v1 xfer, v2;          // raise event e with payload (v1, v2) where v1 is passed  by “xfer” and v2 is passed normally

I have added a few samples that demonstrate the use of “xfer” and “swap”:
https://github.com/p-org/P/blob/master/Tst/RegressionTests/Feature2Stmts/Correct/LinearPingPong/LinearPingPong.p
https://github.com/p-org/P/blob/master/Tst/RegressionTests/Feature2Stmts/Correct/linear1/linear1.p
https://github.com/p-org/P/blob/master/Tst/RegressionTests/Feature2Stmts/Correct/lock/lock.p
https://github.com/p-org/P/blob/master/Tst/RegressionTests/Feature2Stmts/Correct/ref1/ref1.p
https://github.com/p-org/P/blob/master/Tst/RegressionTests/Feature2Stmts/StaticError/linear/linear.p
https://github.com/p-org/P/blob/master/Tst/RegressionTests/Feature2Stmts/StaticError/linear2/linear2.p

The sample lock.p is particularly interesting because it shows how to mimic coarse-grained shared-memory programming in P.  The ability to attach “xfer” to send makes this example possible.  

With the addition of “xfer” and “swap”, I feel that I have closed the gap between P and other langauges for safe concurrent programming such as Rust.  Rust goes beyond P in that its type system allows objects to be concurrently read-shared.  On the other hand, that particular feature is perhaps the most complicated as well.  Linearity tracking and memory management in P is still comparatively simple.

Let me know if you have any feedback.  I am not too crazy about the keywords “xfer” and “swap”, especially the latter.  Another choice for “swap” might be “xchg”.  The placement of “xfer” or “swap” after the variable rather than before has to do with parsing convenience.  I don’t know what is better.

**Comment by pdeligia** [comment]
This is very interesting @shazqadeer. What you describe above sounds very reasonable, and the use of `xsfer` and `swap` seem straightforward enough from a programmability point of view. Regarding the position of `xsfer` and `swap`, I actually like it as it is (declared after the variable), but I am sure this is very subjective, so it would be great to get more opinions on this. I also like the keyword `swap`, much more than `xchg`. I think `swap` might be easier to recognise when reading a P program (`xsfer` and `xchg` are in a way too similar).

**Comment by paulthomson** [comment]
I really like it! I think I would need to write a lot of P code to truely evaluate it though. Here are some potential concerns, although I may have misunderstood some things:

1. I have a large, pure function with parameters. I modify the function and, for convenience, I end up assigning to a parameter (not as a "return" value). Now the function is impure. I may not notice this and/or I may not realise the performance consequences. The same applies if I introduce an assignment to a global. Could a function optionally be marked as pure (and the compiler will check this) to help alleviate this?

2. Similar to (1). What if I use swap or xfer when calling a pure function? If that is an error and I want to ensure parameters are not copied for efficiency, then I will have to update all callsites if the function becomes impure. 

3. I have a function. I can't tell how to call this function by looking at its signature. Does it "return" a value by assigning to a parameter? Perhaps it assigns to a parameter but only for convenience; the value is not supposed to be "returned" but I should not use swap if I want to maintain the original value of a parameter. Or perhaps it does not assign to any parameters and using swap would therefore be wise for better performance. I will have to study the body of the function to find out and future changes to the function body may mess up my code because there are no guarantees given by the signature.  

4. Similar to (3). A function can basically behave differently depending on how it is called. This makes it hard to reason about a function body. Is that assignment used to "return" a value? It depends. 

5. I have a function that does not modify its parameters, but it must modify a global. Can I ensure that callers won't accidentally copy all parameters? Again, I guess this relates to the signature. 

6. Can I xfer/swap a parameter to/with a global variable (indirectly?)? This would be useful. What if I pass a parameter via swap, and the function body xfers this parameter? That might be useful. What if I pass the parameter normally? 

7. My immediate thought is: I want to always pass by swap. It would be nice if a function signature could show that the function will not modify a parameter.

I think I mainly want to be able to add more information to function signatures, but I have not thought about it in depth. And maybe I would like readonly/const parameters.

Subjective stuff: I like swap. I think I like the placement. Maybe I would prefer `ref` for passing a parameter via `swap`. And maybe a `swap x,y;` statement. Maybe `move` could be an alternative to `xfer`, although perhaps `move` is sometimes associated with copying, which could be confusing. But C++11 has "move semantics".

**Comment by shazqadeer** [comment]
Thanks for the feedback. I respond to the points raised by @paulthomson .

1. An optional and compiler-checked pure annotation on a function is a great idea.  I will add it to P.

2. Yes, "swap" or "xfer" can be used to call a pure function.  The compilation of only that call site will be affected.  The other call sites that do not use "swap" or "xfer" are compiled in the standard manner without cloning the parameters.

5. If a function modifies a global, it is not pure and parameters to a call will be cloned unless "xfer" or "swap" is used.  Using the optional "pure" annotation (described in my response to 1), the programmer can get in the program text an indication whether parameters will be cloned or not.

6. The left-hand-side of a "xfer" or "swap" assignment is an arbitrary global or local l-value expression, although the right-hand-side must be a local variable or a formal parameter.  Formal parameters of a function can be involved in "xfer", either via a "xfer" assignment or by passing to a function call as an "xfer" argument.

3, 4, 7. The current design does not require any changes to function signatures.  All the machinery is at call sites.  It sounds like annotations on the function itself might be helpful in clarifying intent. I can imagine two possible annotations on a formal parameter---"available" and "immutable" (or "const").    The annotation "available" indicates that the storage allocated for the parameter is still available when the function terminates (for all possible paths). The annotation "immutable" is stronger than "available"; it addition to the requirements for "available" it also states that the function must not modify this parameter.  The P compiler already checks that if a formal parameter is passed by "swap" at any call site, it must be "available" at exit.  The "available" annotation simply makes it explicit in the program text.  I think that the "immutable" annotation should be optional.  I don't know whether to keep the "available" annotation optional as well or require it for "swap" parameters.

**Comment by akashlal** [comment]
It is natural that, at the time of writing a procedure, to determine what the "out" variables of the procedure are. The caller then determines which of the out variables it cares about. In this sense, it is natural to annotate formals that are returned by a procedure. Call sites then use swap (or not) to actually obtain the value.

**Comment by shazqadeer** [comment]
I have changed the keyword xfer to move.

**Comment by ankushdesai** [comment]
Closing this issue as we are tracking cleaning up of linear types here: #203
