### ISSUE TITLE
Can P be compiled with dotnet core?

### ISSUE THREAD

**Issue by BusyJay** [p-org/P#101]
Hi,

I notice that the build instructions use mono to build P on Linux and OS X. Can I use dotnet core to do the job too?

**Comment by thisiscam** [comment]
Theoretically I don't see how P can't be compiled with dotnet core.

However, the current project still uses msbuild tools(i.e. .sln files), and I'm not really familiar about the progress of dotnet core since I remember it uses some json file as build files? 

Notice that P compiler uses some UseTask directives in the build file, so we can't create brandly new json specifications that mimics the current system easily I think.

Though I do agree that supporting dotnet core seems like a step up on the cross-platform-ness, as mono is third party and now we have to painfully let the user build mono 4.5 from source.

**Comment by shazqadeer** [comment]
This question has popped up again.  If we want P to be a serious contender in the robotics space, ensuring that the tools work on .NET Core would be a great step forward.  Any volunteers for investigating this issue?

**Comment by ankushdesai** [comment]
I agree. 
Also, I had to remove PTester from the linux build system as it recently added a dependency on PSharp and I was not able to build PSharp using mono.

The linux build right now also generates a lot of warnings.

If there are no takers for this then I can take a stab at it during summer after the semester ends.
May be @thisiscam would be interested in it too.

**Comment by thakkarparth007** [comment]
PSharp wasn't being built by mono directly. It had references to `/home/parth/PSharp/./projects/...`, but the projects folder was created as `.\/projects`. On copying `.\/projects` to `projects`, MonoDevelop was able to build PSharp without any further changes. Tools/Visualization wasn't being handled by MonoDevelop, but Build still passed.

**Comment by alexreinking** [comment]
The forthcoming new compiler toolchain is built entirely on .NET Core.

**Comment by ankushdesai** [comment]
The new compiler toolchain is part of the master branch now.

**Comment by ankushdesai** [comment]
P Compiler is completely based on dotnet core 3.1 now. Closing this issue.
