### ISSUE TITLE
Relaxing the rules for composition (private machines)

### ISSUE THREAD

**Issue by ankushdesai** [p-org/P#115]
Suppose P and Q contain some common machines.  We can allow the composition of P and Q provided the following conditions hold for each common machine m:
1.	Machine m is private both in P and in Q;
2.	The map L(m) in P is identical to the map L(m) in Q.

*Shaz Email*
I did manage to remind myself of what happens with the rename operator.  My understand is the set of machines of a module is always the “renamed” machines and you maintain a RenameMap from the renamed names to the original names to do code lookup.  Disjointness of machine names in the composition is with respect to renamed names.  Is my understanding correct?

If my understanding is correct, then you have to check more conditions similar to 2 that the common renamed names in P and Q are isomorphic, for example, they map to the same original machine name.  When you add the safe operator, I imagine you have something like a SafeMap and a check for that would also have to be added.

If we want to push this proposal through, we should change the EXPORT rule slightly to minimize the addition to L.  The less stuff there is in L, the more chances that things will match during composition.  In particular, we should add to L a binding (\alpha, m) only if it is useful, i.e., \alpha is in the creates list of m.  Condition (3) in “Machine link map is consistent” will change slightly as a result.

**Comment by shazqadeer** [comment]
This discussion needs to be revisited because of recent changes to the module system in the latest version of the "compositional reasoning" paper.  Here is my proposal:

1. A machine automatically becomes private once all events received by it have become private.
2. A private machine should be automatically renamed to a globally unique name different from any other machine name.  We need to design an algorithm to coming up with such unique names.
3. We should not allow renaming of a private machine.  The unique name assigned to it in step 2 above is its final name.
4. Module composition continues to work as usual and is guaranteed never to be declared illegal because of a conflicting name for some private machine.

**Comment by ankushdesai** [comment]
@shazqadeer Is this discussion relevant with respect to the latest version of formalism ?

**Comment by shazqadeer** [comment]
I think it is relevant but it is very far in the future and needs to be revisited.  If we choose to revisit, we should create a new issue.  Therefore, I am closing it.
