### ISSUE TITLE
Splitting a machine declaration across multiple files

### ISSUE THREAD

**Issue by shazqadeer** [p-org/P#120]
@ellab123 is doing a project to translate driver state machines written in a P-like visual language into a textual P program.  Each driver state machine is split into two files---sm.json, a JSON-formatted representation of the states and transitions and a text file sm_models.txt containing the machine variables and implementations of model functions referred to in sm.json.  It would be really nice if the latter file was by itself a valid P file sm_models.p because then we could build the following nice tool flow:

1. Automatically generate sm.p from sm.json
2. Pass sm.p and sm_models.p to pc.exe 

But the above is possible only if we allow a machine declaration to be split across multiple files, something akin to partial classes in C#.  How difficult would it be to implement this feature?

**Comment by ankushdesai** [comment]
I don't think this is **too** much work.
We need to extend the parser so that we allow multiple declarations of a machine if annotated as "partial".
The union of all the attributes (declared partially across files) of a machine is easy as we are generating separate decls for them. The StateDecl, TransitionDecl, FunDecl.... have owner information (the owner information will have to updated) in them and hence it does not matter whether they are declared in same or separate files.

Once all the decls generated from the separate file are unioned together it would look similar to what we have right now and hence there would not be much changes in the checker phase.

Note that this still assumes that partial declarations are in the same compilation unit.

**Comment by shazqadeer** [comment]
Yes, I am fine with assuming all the declarations are in the same compilation unit.

Do we really need the partial keyword?  We can probably avoid it by always doing a union of all machines declared under a particular name.  Is that too error prone?

My understanding of the parser is that the MachineDecl structure is allocated for the enclosing machine on demand and then picked up by all declarations that have a MachineDecl inside it.  We probably cannot retain this logic since different MachineDecl's will have different spans associated with them.  One problem I see is how to generate a single MachineDecl even though there are multiple declarations?

**Comment by ankushdesai** [comment]
I think it is error prone, in cases where the union is unexpected.
With **partial** annotation, the programmer is very explicit that this machine declaration can reappear and should be unioned. For the rest, raise an error of double declaration of machines.
The rules would be similar to C# where if a machine is declared partial then it is partial everywhere.

For the second point. The solution I was thinking was replacing the owner information to just the machine name instead of the entire machineDecl which is the case right now.
This way we don't have to have a handle to complete MachineDecl but just need to know the machine name. Will this break anything? During the checker phase, we can get the machineDecl info from the machine name?

**Comment by shazqadeer** [comment]
I am fine with the **partial** annotation.

Your solution with machine names sounds reasonable.  I don't think it will break anything.  But, there is still the issue of creating a single MachineDecl from multiple partial machine declarations in the text.  Which particular declaration should the MachineDecl correspond to?

**Comment by ankushdesai** [comment]
I was thinking that during the parsing phase if a machine is declared as partial then there will be no MachineDecl generated for it (but we will generate a PartialMachineDecl(name:String)).
A MachineDecl for it will be created during checker phase by combining all the relevant attributes together, using the PartialMachineDecl and other StateDecl, etc to get the start state and so on.

**Comment by shazqadeer** [comment]
That sounds good to me.

**Comment by shazqadeer** [comment]
This feature is implemented and checked in master.  A machine can be split across multiple files in the same compilation unit by putting the partial annotation on it.  A sample is available in the folder <PRoot>\Tst\RegressionTests\Feature1SMLevelDecls\Correct\Partial.
