### ISSUE TITLE
Combine compiler and linker phase

### ISSUE THREAD

**Issue by ankushdesai** [p-org/P#134]
Currently, linker only accepts one .p file during linker phase.
This constraint needs to be relaxed to enable writing testscripts split across files.

**Comment by shazqadeer** [comment]
Have you tried it? I thought multiple .p files at the linker phase are accepted.

**Comment by ankushdesai** [comment]
I didn't finish that part of the implementation and currently, it only parses only one .p file.
I will fix this.

**Comment by shazqadeer** [comment]
I would like to suggest a different approach in which the linker and compiler phases are brought closer together through the following steps:
1. Unify the parsing of input P files so that a file provided in the compiler phase is allowed to contain module, test, and implementation declarations.
2. The /link option is an indicator to perform some checks that all used symbols are defined.  This option will not have any effect on code generation except when C output is desired in which case the output file that is called linker.c today would be concatenated to the output file foo.c where foo is the name of the compilation unit.

The main advantage of this approach is build simplification when code generated by the P compiler is compiled together with hand-written code in the host language.  The P compiler can always be run before building the code in the host language.  Every P file is treated the same and can be included in the project with the same build target name.  I believe that this change would make it much easier to integrate P into build systems designed for other languages such as C/C++ or C#.

**Comment by ankushdesai** [comment]
One of the reasons why module system analysis was pushed to linker phase (and the ModP parser was kept separate) was that we wanted to keep module system as a wrapper on top of P until we are confident.
This step is towards making ModP mainstream. With this in mind, I agree with your next steps. 

I am still not very convinced about why we need the linker checks to be separate. Since the dependency relation is a DAG, why don't we perform the linker time checks during the compilation phase itself? 
I think that these **warning** will be helpful to the programmer that these symbols are not defined (or there are multiple declarations) and will eventually lead to final generated code compilation errors.

**Comment by shazqadeer** [comment]
Why are you saying the dependency relation is a DAG?  It could be circular because of extern fun and machine declarations.

**Comment by ankushdesai** [comment]
I take back the DAG comment. 

We will have to allow sends, receives, exports and creates annotations on extern machine decls.

**Comment by shazqadeer** [comment]
I am happy to discuss whether we want to restrict the dependency relation to DAG but that is a separate discussion which is orthogonal to the unification of compiler and linker phase.

I am still trying to process your suggestion.  If all linker checks are performed during compilation itself, then I imagine that the /link option could be dropped for all outputs except for C code.  The reason that it cannot be eliminated for C code generation is that /link not only creates more checks but also indicates that more code needs to be generated.  Is my understanding correct?  

Also, you referred to violations of linker checks as warnings.  That indicated to me, even though you did not say it explicitly, that linker errors are less serious than compiler errors.  Perhaps, your intention is that linker errors for all but the "final" compilation unit that puts it all together should be treated as helpful warning.  Of course, for the final compilation unit, these warnings are serious.  

If we allow circular dependencies and also perform linker checks always, then it is possible that there is no order of compilation that will result in absence of linker warnings at each step.  But it is clearly possible to ignore intermediate linker warnings and pay serious attention only to the warnings for the "final" compilation unit which should be absent regardless of the dependency graph.

**Comment by ankushdesai** [comment]
Yes, you are right.
We cannot eliminate /link option for the C code gen, this is mainly because of the enums (integers indexes) corresponding to events, IorM, etc. that have to be initialized for the entire program.
But for the rest of the pipeline, we can eliminate the /link option.

I am more inclined towards eliminating /link as it is less work for the programmer and I don't see any real benefit of keeping it separate.

I agree with your assessment that the programmer only needs to worry about the warnings for the final compilation unit. If ignored will lead to errors when compiling the generated code.

One other question:
Is my comment above correct, that if the programmer ignores warning it will always lead to compiler errors in the generated code, is it possible that the generated code will be compiled but will lead to a runtime-failure?

**Comment by ankushdesai** [comment]
I think it is possible that if a programmer ignores linker warnings then it will lead to runtime failures.

For example, in extern declaration of a function if the programmer under-specifies creates that does not match the definition, then it could lead to a runtime failures.

Similar argument holds for extern machine-decls. 

So I am not really sure that ignoring linker warning is safe!

**Comment by shazqadeer** [comment]
To answer your question, we should first clarify what is the set of linker checks.  I don't think we should think of all checks that are being performed today when /link option is passed as linker checks.  I expect most of them will become compiler checks, e.g., all the well-formedness checks for modules.  As a rough approximation, I would like to consider only those errors that are about used symbols that don't have a definition for them as linker checks.  Since you are most familiar with the set of checks being performed by /link option, you should try to articulate how they get partitioned between compiler and linker checks in the new setup.

**Comment by ankushdesai** [comment]
Ok, got it. 
I agree with your proposal:
1) Combine the parser for Compiler and Linker.
2) Move the checks performed during Linker phase into Compiler phase. Some of these checks which are with respect to undefined symbols will become warnings but rest of them will remain error.
3) We will still support /link option (possibly rename it /linkC) which will be only doing linker level code gen for C ouput. /linkC will not do any checks only code-gen with respect to C.

Once we have consensus on this, we can start discussing the changes in summary file output, additional checks to be added, and code gen with respect to module decl, etc.

**Comment by shazqadeer** [comment]
Yes, this looks good to me.

**Comment by ankushdesai** [comment]
@shazqadeer Time to reopen this issue.

**Comment by ankushdesai** [comment]
@shazqadeer (1) has been taken care of in the removelinker branch.

**Comment by ankushdesai** [comment]
Not relevant for the new compiler
