### ISSUE TITLE
On error print stack trace

### ISSUE THREAD

**Issue by paulthomson** [p-org/P#18]
Many built-in assertions in the Zing generated code do not mention the line number where the error occurred in the original P file. E.g. 

```
Error:
P Assertion failed:
Expression: assert(0 <= index && index < size)
Comment: index out of bound
```

This may be fine for small event handlers, but is very difficult when there are many function calls, etc. and many possible places where the error could have occurred.

**Comment by shazqadeer** [comment]
This problem is tough to solve in general.  It is similar to having an assertion in a library function which is being called from all over the place.  Matters are worse for Zing error traces because we do not have a debugger for these traces.  Would it help if I added the print functionality we have talked about? You could then do classical print debugging.

**Comment by paulthomson** [comment]
Oh yes that feature would still be very helpful! Actually, so would printing out a stack trace. I guess it will be a Zing stack trace, but still. 

Perhaps in the future, some of the stack frames could include mappings to lines in the P code as well!

**Comment by shazqadeer** [comment]
The plan now is to eliminate the Zing language from the P pipeline and go directly to C#.  We are freezing feature addition in the P to Zing path.
