### ISSUE TITLE
Add regressions.

### ISSUE THREAD

**Issue by desaiankush** [p-org/P#2]
There are three recent additions in P:
1) Static functions
2) Receive statements
3) Local variables

Need to add regressions for thorough testing of these new features.

**Comment by shazqadeer** [comment]
I have checked in fixes for handling static functions correctly.  I agree that we need regressions for static functions in the test folder.  We already have regressions for 2 and 3 but it would be good to examine them and add more.

@desaiankush: Please add the sample you sent me as regression.  Also, add the PingPong sample in PrtDist since it has static functions.

**Comment by desaiankush** [comment]
Added regressions for static functions.
