### ISSUE TITLE
Invalid Composition Operation

### ISSUE THREAD

**Issue by suvamM** [p-org/P#200]
I have an event `ePing: machine`, and the following machines:
```
machine Ping {
  var PongMachine : machine;
  start state Init {
    entry {
      PongMachine = new Pong();
      send PongMachine, ePing, this;
    }
    on ePing do SendPing;
  }
  
  fun SendPing (pMachine:machine) {
     send pMachine, ePing, this;
  }
}
```
The `PongMachine` is similar, executing `SendPing` on receiving `ePing`, with `this` as payload. When I try to compose the machines in a test script:

```
module System = 
{
    PingMachine, PongMachine
};

test Test0[main = Test_1_Machine]: (assert Safety in (compose { Test_1_Machine }, System));
```
I get the following error during compilation:

`[testscript.p:6,63] invalid composition operation. output sends are not disjoint, ePing belongs to the sends of the composed module`

What is the issue here?

**Comment by ankushdesai** [comment]
If you do not provide any sends annotation on the machine then the default is all possible events in the program.

For compositional reasoning, it is required that the modules have disjoint send events-set.

I am assuming that in this case you are not really exploring "sound" compositional testing so you can create larger modules by unioning multiple modules.

So there are three options:
- Add sends annotation to each machine and ensure that sends events-set of each module is disjoint.
- Use 'union' instead of 'compose'. 
```test Test0[main = Test_1_Machine]: (assert Safety in (union { Test_1_Machine }, System));```
- Put all the machines inside a single module (if you are doing monolithic testing).
```test Test0[main = Test_1_Machine]: (assert Safety in ({ Test_1_Machine, PingMachine, PongMachine }));```

**Comment by ankushdesai** [comment]
Were you able to resolve this problem?

**Comment by suvamM** [comment]
Sorry for the delayed response. 

Unfortunately, I now get the following error during compilation:
`[testscript.p] parse error: line 1:54 no viable alternative at input 'testTest0[main=Test_1_Machine]:(assertSafetyin({'`

My test script file is now simply:

`test Test0[main = Test_1_Machine]: (assert Safety in ({ Test_1_Machine, PingMachine, PongMachine }));`

**Comment by ankushdesai** [comment]
This must be fixed now.

**Comment by suvamM** [comment]
Thanks!
Unfortunately, I continue to get this error message. I am compiling using the Pc.dll
Reopening the issue.

**Comment by ankushdesai** [comment]
Can you please make sure you are using the latest build. I am able to compile the attached example.
Please let me know if you are not able to compile this sample and what is the difference in your code?
[PingPong.zip](https://github.com/p-org/P/files/2924301/PingPong.zip)

**Comment by suvamM** [comment]
This was an issue with build version. Closing this. Thanks.
