### ISSUE TITLE
removing type inference from golden output

### ISSUE THREAD

**Issue by shazqadeer** [p-org/P#24]
I am thinking about dropping the inferred types from golden output of the regression tests.  I find there is a lot of noise there that needs to be sifted through whenever I make a change to the compiler.  Any opinions?

**Comment by desaiankush** [comment]
I find it important. Whenever we make changes in the typing rule, the
inferred types changes. It is important to have the golden files so that we
make sure that we did not introduce any bug in the type-checker and the
changes are expected.
If there is some other way easier way of making sure that the type-checker
is correct, I am fine with removing the golden files.

**Comment by shazqadeer** [comment]
The way I figure it out is to write test cases for the various type errors and then correct programs that should type check.  For the latter, absence of any typing error is only partial information.

**Comment by shazqadeer** [comment]
I am going to eliminate the type inference output from golden files in the next couple of days.  Please holler if you have strong objections.  My decision is based on the following considerations:
1. I never use the type inference output to detect a regression failure.  A regression failure is indicated by the unexpected presence or absence of an explicit error message.
2. The type inference output is noisy.  Often, a change to the type checker results in a line moved from one place to another in the output creating many regression failures that I have to wade through.  This noise also increases the chance that I will miss a real problem.

**Comment by shazqadeer** [comment]
Ella's last checkin eliminated the type inference output from the golden files.
