### ISSUE TITLE
Running the model checking tool with my code is slow

### ISSUE THREAD

**Issue by pinzaghi** [p-org/P#355]
I reimplemented the 2PC protocol (very influenced by the tutorial implementation) but with a different set of states and ignoring the Client.

My [code](https://github.com/pinzaghi/protocols-examples/tree/main/TwoPhaseCommit/P) compiles, and based on some tests, it seems to work, or at least not to crash with trivial cases.

Running the tool  ``pmc netcoreapp3.1/TwoPhaseCommit.dll -m PImplementation.Test0.Execute`` outputs the following:

```
. Testing netcoreapp3.1/TwoPhaseCommit.dll
... Method PImplementation.Test0.Execute
Starting TestingProcessScheduler in process 30634
... Created '1' testing task.
... Task 0 is using 'random' strategy (seed:3969422363).
..... Iteration #1
... Testing statistics:
..... Found 0 bugs.
... Scheduling statistics:
..... Explored 1 schedule: 1 fair and 0 unfair.
..... Number of scheduling points in fair terminating schedules: 100000 (min), 100000 (avg), 100000 (max).
..... Exceeded the max-steps bound of '10000' in 100.00% of the fair schedules.
... Elapsed 4.0642763 sec.
. Done
```

It took 4 seconds to complete one schedule. When I run it in verbose mode, I don't see anything strange, it continues the protocol more than 5k iterations until it reaches the step bound. My implementation (and I think is also the case for the tutorial) does not stop, it executes indefinitely.

Why is so slow? 

I'm not an expert on model checking tools, and maybe I'm not understanding something, but the program seems to do the job.

**Comment by ankushdesai** [comment]
Hi @pinzaghi, It seems from the log that your model has long running executions.
`Exceeded the max-steps bound of '10000' in 100.00% of the fair schedules.`

One of the requirements for using the P checker is that your models have finite executions and your test harness are finite generating finite inputs. Is it possible that your test driver is generating infinite inputs or that most of the executions in your system are infinite (long, for example because of time outs or cycles?)

**Comment by pinzaghi** [comment]
Indeed, the way I implemented it is with infinite executions. Now I see with more detail the tutorial, the clients send a constant amount of transactions, that's why is a finite execution.

Thanks.

**Comment by ankushdesai** [comment]
Yup, Thanks!!
