### ISSUE TITLE
Optimize PrtAssert overhead

### ISSUE THREAD

**Issue by lovettchris** [p-org/P#52]
Running with PrtAssert I get 226052 steps per minute and without I get 241069, so PrtAssert is currently costing about 6% which seems a bit high.  It would be nice to reduce that cost somehow or make it optional under #if DEBUG flag so we can build a "fast" build when we need one.

One simple optimization is to define PrtAssert like this:
# define PrtAssert(c,m) if (!(c)) { _PrtAssert(c,m); }

Inlining the test gives back about 3% of the cost with a minimal binary size increase.  Binary size increases from 238337 to 238433, which is only 96 bytes, about 0.04%.

Other improvements could be done by pulling PrtAssert out of any tight loops.

**Comment by shazqadeer** [comment]
6% for PingPong is indeed significant.  The overhead may go up if there are larger values floating around.  #if DEBUG solution looks good to me.  If DEBUG is not set PrtAssert becomes a no op.

**Comment by lovettchris** [comment]
Turns out the overhead can be much higher if you are passing around large data structures.  So I checked in my fix under a new #define PRT_NO_ASSERT flag.  The Release build sets this and gets much higher performance than the Debug build.  If you pass a 10 element sequence in pingpong you will see a 18% perf improvement in the release build if you turn on PRT_NO_ASSERT.  Between Release and Debug build you will see a 5 times improvement.

**Comment by desaiankush** [comment]
@lovettchris Do you think we can close this issue now ?

**Comment by lovettchris** [comment]
Not sure I think Shaz had some more thoughts about this, he wanted to clarify which PrtAsserts should really be PrtExceptions and remain in the retail bits for that purpose.

**Comment by shazqadeer** [comment]
I had a chat with Ethan, who designed the PrtAssert and PRT_DBG_ASSERT mechanism.  PRT_DBG_ASSERT macro exists only in debug build and is compiled away in release build.  It should be use for guarding against P runtime bugs.  PrtAssert is supposed to be on in both debug and release builds and is meant to guard against illegal use of P runtime APIs by clients.  The PrtAssert mechanism is less than ideal because it does not distinguish between the generated C code and arbitrary foreign code.  Ethan conceded that PrtAssert could create inefficiency for large data values.  But he does not want to do away with it altogether.  He suggested digging deeper to figure out which particular call to PrtAssert is creating the most overhead for the linear transfer example.

**Comment by ankushdesai** [comment]
@shazqadeer @clovett Do you remember what was the status of this issue?

**Comment by shazqadeer** [comment]
The final status of this issue is the following: PRT_NO_ASSERT is available for eliminating all runtime assertions.  This is not set by either the Debug or the Release build.  It has to be explicitly used.
