### ISSUE TITLE
Zinger cannot handle foreign functions inside expressions

### ISSUE THREAD

**Issue by lovettchris** [p-org/P#67]
I have this function:
 
    model fun IsNaNFloat32(op1: float32) : bool
    {
       return $;
    }

If I use it like this:

    var f: float32;
    if (IsNaNFloat32(f)) {
    }

then Zinger complalins with this error:
    error: this function must be pure. Impure functions can only be called like "foo(...);" or "x = foo(...);"

If I move the function out to a separate statement:

    var f: float32;
    var b: bool;
    b = IsNaNFloat32(f);
    if (b) {
    }

then Zinger works, but I shouldn't have to do that.

**Comment by shazqadeer** [comment]
I am looking into this issue.  The translation of $ appears to be completely broken to me.  The only thing that will work right now is 
if ($) {
...
}
that is, $ at the top level in an expression.  If $ is nested in an expression, it won't work. The problem you are seeing is restriction I imposed to ensure that $ do not get dynamically invoked when evaluating a function call embedded in an expression.  But just doing that is not a solution either because nesting $ directly in the expression creates the same problem.  I need to re-think the translation.

**Comment by shazqadeer** [comment]
Here is the new story with $ and $$.  They are still treated as calls to impure functions.  So, they cannot appear nested in expressions.  I have tightened the type checker to check for this (it wasn't doing so earlier and consequently allowing bogus code to be generated).  At the same time, I allow impure functions to be called as 

if (foo())

or 

while (foo())

or 

return foo();

So your example should work now.  Note that the following will still not be allowed

if (x < y && $) { ... }

You will have to rewrite it as 

if (x < y) {
    if ($) { ... }
}

I thought hard about allowing nested $ but ultimately decided not to do it because of increased complexity in translation and potential bad impact on state caching, an important feature of Zinger search.

**Comment by shazqadeer** [comment]
Closing this issue.
